# Generated by Django 5.1.3 on 2025-01-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_skill_employerprofile_freelancerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='languages',
            field=models.ManyToManyField(blank=True, to='users.language'),
        ),
    ]
