# Generated by Django 5.1.3 on 2025-01-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_language_freelancerprofile_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('freelancer', 'Freelancer'), ('employer', 'Employer')], default='freelancer', max_length=10),
        ),
    ]
