# Generated by Django 5.1.3 on 2025-01-11 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_role_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='user',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('freelancer', 'Freelancer'), ('employer', 'Employer')], max_length=10)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('completed_projects', models.PositiveIntegerField(default=0)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('posted_projects', models.PositiveIntegerField(default=0)),
                ('languages', models.ManyToManyField(blank=True, to='users.language')),
                ('skills', models.ManyToManyField(blank=True, to='users.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='EmployerProfile',
        ),
        migrations.DeleteModel(
            name='FreelancerProfile',
        ),
    ]
