# Generated by Django 5.1.3 on 2025-01-11 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_language_name_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_type',
        ),
    ]
