# Generated by Django 5.1.3 on 2025-01-11 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='client',
            new_name='employer',
        ),
    ]
