# Generated by Django 5.1.3 on 2025-01-15 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_client_rating_employer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
