# Generated by Django 5.1.3 on 2025-01-14 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('payment_type', models.CharField(choices=[('CARD', 'CARD'), ('PAYLOV', 'PAYLOV'), ('PAYME', 'PAYME')], max_length=50, verbose_name='Payment type')),
                ('method_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Method type')),
                ('request_headers', models.TextField(null=True, verbose_name='Request Headers')),
                ('request_body', models.TextField(null=True, verbose_name='Request Body')),
                ('response_headers', models.TextField(null=True, verbose_name='Response Headers')),
                ('response_body', models.TextField(null=True, verbose_name='Response Body')),
                ('response_status_code', models.PositiveSmallIntegerField(null=True, verbose_name='Response status code')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='Currency')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=32, verbose_name='Status')),
                ('remote_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Remote id')),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='TAX Amount')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid at')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Canceled at')),
                ('payment_type', models.CharField(choices=[('CARD', 'CARD'), ('PAYLOV', 'PAYLOV'), ('PAYME', 'PAYME')], verbose_name='Payment Type')),
                ('extra', models.JSONField(blank=True, null=True, verbose_name='Extra')),
                ('is_notification_sent', models.BooleanField(default=False, verbose_name='Is notification sent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'Transaction',
                'ordering': ('remote_id',),
            },
        ),
        migrations.CreateModel(
            name='PaymentRetryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('attempt_number', models.PositiveSmallIntegerField(default=1, verbose_name='Attempt number')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Payment Gateway Response')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retry_logs', to='payment.transaction')),
            ],
            options={
                'verbose_name': 'Payment Retry Log',
                'verbose_name_plural': 'Payment Retry Logs',
                'db_table': 'PaymentRetryLog',
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=32, verbose_name='Status')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Changed at')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='payment.transaction')),
            ],
            options={
                'verbose_name': 'Transaction History',
                'verbose_name_plural': 'Transaction Histories',
                'db_table': 'TransactionHistory',
                'ordering': ('-changed_at',),
            },
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('deleted', 'Deleted')], default='pending', max_length=20, verbose_name='Status')),
                ('card_number', models.CharField(max_length=16, verbose_name='Card Number')),
                ('cid', models.CharField(max_length=3, verbose_name='CID')),
                ('expire_date', models.CharField(max_length=5, verbose_name='Expire Date')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Is Confirmed')),
                ('vendor', models.CharField(choices=[('humo', 'Humo'), ('uzcard', 'Uzcard')], default='humo', max_length=10, verbose_name='Vendor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Card',
                'db_table': 'UserCard',
                'ordering': ['-created_at'],
                'unique_together': {('status', 'is_confirmed')},
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payment.usercard', verbose_name='Card id'),
        ),
    ]
